#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : murrine
Version  : 0.98.2
Release  : 9
URL      : http://ftp.gnome.org/pub/GNOME/sources/murrine/0.98/murrine-0.98.2.tar.xz
Source0  : http://ftp.gnome.org/pub/GNOME/sources/murrine/0.98/murrine-0.98.2.tar.xz
Summary  : Murrine GTK+ Theme Engine
Group    : Development/Tools
License  : GPL-3.0 LGPL-2.1 LGPL-3.0
Requires: murrine-data
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(pixman-1)

%description
This is Murrine GTK+ engine. This source code provides only the engine, get the themes @ gnomelook.org.

%package data
Summary: data components for the murrine package.
Group: Data

%description data
data components for the murrine package.


%prep
%setup -q -n murrine-0.98.2

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/gtk-2.0/2.10.0/engines/libmurrine.so

%files data
%defattr(-,root,root,-)
/usr/share/gtk-engines/murrine.xml
